---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Ensure HAProxy is enabled and restarted
  service:
    name: haproxy
    state: restarted
    enabled: true
