all:
  children:
    haproxy:
      hosts:
        bastionhost1:
          ansible_host: 192.168.2.250

    rke2_cluster:
      children:
        rke2_servers:
          hosts:
            master1:
              ansible_host: 192.168.2.201
            master2:
              ansible_host: 192.168.2.202
            master3:
              ansible_host: 192.168.2.203

        rke2_agents:
          hosts:
            worker1:
              ansible_host: 192.168.2.211
            worker2:
              ansible_host: 192.168.2.212
            worker3:
              ansible_host: 192.168.2.213
            worker4:
              ansible_host: 192.168.2.214
            worker5:
              ansible_host: 192.168.2.215
            worker6:
              ansible_host: 192.168.2.216

